In [1]:
import numpy as np


In [3]:
arr = np.random.randn(7,4)
arr

array([[ 0.40098767,  0.53096764,  2.10817089,  1.71447155],
       [ 0.38844479, -0.85775283, -0.15523216, -0.38935977],
       [ 0.67767488, -1.2863455 , -2.02723762,  0.70431755],
       [ 1.04074532, -0.6082969 , -1.15236448, -0.76419617],
       [ 1.11817435,  0.18435372, -0.075225  , -0.04467092],
       [-0.26760093, -0.32838912,  1.31349733,  1.38389017],
       [ 0.54387744, -0.0516591 , -0.19585202,  0.86382304]])

In [4]:
arr[:2,1:2]

array([[ 0.53096764],
       [-0.85775283]])

In [6]:
a=arr[:2,1:2]
a.shape

(2, 1)

In [7]:
b=arr[:2,1]
b.shape

(2,)

In [8]:
b[1]

-0.8577528271841608

In [9]:
bool = np.array([True,False,True,False,False,False,False])


In [11]:
c=arr[bool,1:]

In [12]:
c

array([[ 0.53096764,  2.10817089,  1.71447155],
       [-1.2863455 , -2.02723762,  0.70431755]])

In [13]:
c[0]=1

In [14]:
c

array([[ 1.        ,  1.        ,  1.        ],
       [-1.2863455 , -2.02723762,  0.70431755]])

In [15]:
arr

array([[ 0.40098767,  0.53096764,  2.10817089,  1.71447155],
       [ 0.38844479, -0.85775283, -0.15523216, -0.38935977],
       [ 0.67767488, -1.2863455 , -2.02723762,  0.70431755],
       [ 1.04074532, -0.6082969 , -1.15236448, -0.76419617],
       [ 1.11817435,  0.18435372, -0.075225  , -0.04467092],
       [-0.26760093, -0.32838912,  1.31349733,  1.38389017],
       [ 0.54387744, -0.0516591 , -0.19585202,  0.86382304]])

In [17]:
arr[bool,1:] = 1
arr

array([[ 0.40098767,  1.        ,  1.        ,  1.        ],
       [ 0.38844479, -0.85775283, -0.15523216, -0.38935977],
       [ 0.67767488,  1.        ,  1.        ,  1.        ],
       [ 1.04074532, -0.6082969 , -1.15236448, -0.76419617],
       [ 1.11817435,  0.18435372, -0.075225  , -0.04467092],
       [-0.26760093, -0.32838912,  1.31349733,  1.38389017],
       [ 0.54387744, -0.0516591 , -0.19585202,  0.86382304]])

In [22]:
a = np.array([np.nan,1,2,3])
b = np.array([1,np.nan,3,4])
np.maximum(a,b)

array([nan, nan,  3.,  4.])

In [24]:
points = np.arange(-5,5,0.01)
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [25]:
x,y = np.meshgrid(points,points)

In [26]:
x

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [27]:
y

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [28]:
x = np.array(['a','b','c','a'])
y = np.array(['a','d','d'])
np.intersect1d(x,y)

array(['a'], dtype='<U1')

In [30]:
np.setdiff1d(y,x)

array(['d'], dtype='<U1')

In [31]:
xx = np.array([1,2])
xx.shape

(2,)

In [32]:
np.random.randint(0,2,size=1000)

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,

In [33]:
import random
l = list()
for _ in range(1000):
    l.append(random.randint(0,1))
l

[0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,


In [35]:
import pandas as pd
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [36]:
obj4['California'] is np.nan


False

In [37]:
obj4['California']

nan

In [39]:
obj4['California'] is None

False

In [40]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [41]:
obj4['California']=np.nan

In [42]:
obj4


California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [43]:
obj4['California'] is np.nan

False

In [44]:
np.nan

nan

In [47]:
text = pd.Series(np.random.randn(10),index =[['a','a','a','b','b','b','c','c','d','d'],[1,2,3,1,2,3,1,2,2,3]])
text

a  1   -0.963828
   2   -1.280585
   3   -0.090631
b  1   -0.323442
   2    0.477828
   3    0.265111
c  1    0.331126
   2    0.888795
d  2    0.152430
   3   -0.969800
dtype: float64

In [48]:
text.index


MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )